### ISSUE TITLE
Incompatible with Ghidra 10.2.2

### ISSUE THREAD

**Issue by JorisVanEijden** [Gravelbones/GhidraDosToolbox#2]
The current  ghidra_10.0.4_PUBLIC_20211229_GhidraDosToolbox.zip is not compatible with the current Ghidra version 10.2.2.

What would be needed to create a new compatible version?

**Comment by Gravelbones** [comment]
Time and energy, of which energy have been lacking. :)
New release created for 10.2.2.

**Comment by JorisVanEijden** [comment]
Much appreciated!
